name: country_picker
description: A flutter package to select a country from a list of countries.

version: 2.0.20

homepage: https://github.com/Daniel-Ioannou
repository: https://github.com/Daniel-Ioannou/flutter_country_picker

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.17.0
  universal_io: ^2.0.5
  flutter:
    sdk: flutter



flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.8.2